// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Coordinator struct {
	Coordinatorid int64
	Firstname     string
	Lastname      string
	Email         string
	Password      string
}

type Project struct {
	Projectid   int64
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type Student struct {
	Studentid    int64
	Email        string
	Firstname    string
	Lastname     string
	Password     string
	Supervisorid sql.NullInt64
	Projectid    sql.NullInt64
}

type StudentMilestone struct {
	ID          int64
	Studentid   int64
	Milestoneid int64
	Status      sql.NullString
	SubmittedAt sql.NullTime
}

type Supervisor struct {
	Supervisorid int64
	Firstname    string
	Lastname     string
	Email        string
	Password     string
}

type SupervisorMilestone struct {
	Milestoneid        int64
	Supervisorid       int64
	Name               string
	Description        sql.NullString
	SubmissionFilename sql.NullString
	DueDate            sql.NullTime
	SequenceOrder      sql.NullInt64
	CreatedAt          sql.NullTime
}
